name = "cyber-mystery-lunch"
main = "worker/index.ts"
compatibility_date = "2024-12-01"
workers_dev = true
assets = { directory = "./public" } # serve /public as static

[durable_objects]
bindings = [
  { name = "GAME_ROOM", class_name = "GameRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["GameRoom"]

[vars]
DEFAULT_MODE = "serious"  # "serious" | "funny"
