name = "cyber-mystery-lunch"
main = "worker/index.ts"
compatibility_date = "2025-08-01"

[assets]
directory = "./public"   # IMPORTANT: serve only the /public folder as static assets

[durable_objects]
bindings = [
  { name = "GAME_ROOM", class_name = "GameRoom" }
]

# Required on Free plan:
[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]

[vars]
DEFAULT_MODE = "serious"
